// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: amino/amino.proto

/* eslint-disable */

export const protobufPackage = "amino";
