// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: cosmos/msg/textual/v1/textual.proto

/* eslint-disable */

export const protobufPackage = "cosmos.msg.textual.v1";
